/**
 * This file was manually created based on Payload Config
 * Normally auto-generated by: payload generate:types
 */

export interface Homepage {
    id: string
    hero?: {
        eventBadge?: {
            text: string
            link: string
            enabled?: boolean
        }
        mainHeading: string
        highlightedText: string
        trailingText: string
        description: string
        ctaButtons?: Array<{
            text: string
            link: string
            variant: 'primary' | 'secondary'
            id?: string
        }>
        socialLinks?: Array<{
            platform: 'github' | 'threads' | 'linkedin' | 'twitter'
            url: string
            id?: string
        }>
        carouselImages?: Array<{
            src: string
            alt: string
            id?: string
        }>
        uptimeBadge?: {
            enabled?: boolean
            percentage: string
        }
    }
    about?: {
        sectionTitle: string
        introduction: string
        skills?: Array<{
            name: string
            icon: 'cloud' | 'terminal' | 'gitbranch' | 'shield' | 'server' | 'database'
            items?: Array<{
                item: string
                id?: string
            }>
            id?: string
        }>
        whyWorkWithMe?: {
            title: string
            paragraph1: unknown // Lexical rich text JSON
            paragraph2: unknown // Lexical rich text JSON
            showCodeBlock?: boolean
        }
    }
    updatedAt: string
    createdAt: string
}

export interface Config {
    globals: {
        homepage: Homepage
    }
}
